---

name:
    gemini-exports
version:
    0.1.0.0
github:
    prikhi/gemini-exports
homepage:
    https://github.com/prikhi/gemini-exports#readme
license:
    BSD3
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2022 Pavan Rikhi
category:
    Web, Finance, Console
extra-source-files:
    - README.md
    - CHANGELOG.md


synopsis:
    Generate CSV Exports of Your Gemini Trades

description: |
    Longer description of package here.

    Maybe include a simple usage example.


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2

default-extensions:
    - DeriveGeneric
    - LambdaCase
    - NamedFieldPuns
    - OverloadedStrings
    - TupleSections
    - TypeApplications
    - TypeOperators
    - ViewPatterns


dependencies:
    - base >= 4.7 && < 5


library:
    source-dirs:
        src
    dependencies:
        - cmdargs >= 0.10 && < 1

executables:
    gemini-exports:
        source-dirs:
            app
        main:
            Main.hs
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - gemini-exports

tests:
    gemini-exports-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - gemini-exports
            - hedgehog
            - tasty
            - tasty-hedgehog >= 1.2
            - tasty-hunit
