---

name:
    gemini-exports
version:
    0.1.0.0
github:
    prikhi/gemini-exports
homepage:
    https://github.com/prikhi/gemini-exports#readme
license:
    BSD3
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2022 Pavan Rikhi
category:
    Web, Finance, Console
extra-source-files:
    - README.md
    - CHANGELOG.md


synopsis:
    Generate CSV Exports of Your Gemini Trades, Transfers, & Earn Transactions

description: |
    @gemini-exports@ is a CLI program that queries the Gemini Exchange's API
    for your Trade History, Transfer History, & Earn History and exports all
    fetched data to a CSV file.

    You can install @gemini-exports@ with Stack: @stack install --resolver
    nightly gemii-exports@. Then run the following to print out your complete
    history:

    @
    $ gemini-exports -k \<API_KEY\> -s \<API_SECRET\>
    time,base-asset,quote-asset,type,description,price,quantity,total,fee,fee-currency,trade-id
    2022-04-20 04:20:00,GUSD,USD,Buy,,1.0,9001.0,9001.0,0.0,USD,900142424242
    @

    See @gemini-exports --help@ for additional options, configuration file
    details, etc.


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2

default-extensions:
    - DeriveGeneric
    - LambdaCase
    - NamedFieldPuns
    - OverloadedStrings
    - TupleSections
    - TypeApplications
    - TypeOperators
    - ViewPatterns


dependencies:
    - base >= 4.7 && < 5


library:
    source-dirs:
        src
    ghc-options:
        - -Wunused-packages
    dependencies:
        - aeson < 3
        - base64 < 1
        - bytestring < 1
        - cassava < 1
        - cmdargs >= 0.10 && < 1
        - containers < 1
        - cryptonite < 1
        - directory < 2
        - http-client < 1
        - http-types < 1
        - mtl < 3
        - raw-strings-qq < 2
        - req < 4
        - safe-exceptions < 1
        - scientific < 1
        - text < 3
        - time < 2
        - xdg-basedir < 1
        - yaml < 1

executables:
    gemini-exports:
        source-dirs:
            app
        main:
            Main.hs
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - gemini-exports

tests:
    gemini-exports-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - gemini-exports
            - hedgehog
            - tasty
            - tasty-hedgehog >= 1.2
            - tasty-hunit
